# This is a basic workflow to help you get started with Actions

name: maven build

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Deploy server
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout development branch from github
      uses: actions/checkout@v3

    - name: Set up jdk
      uses: actions/setup-java@v3
      with:
       distribution: 'zulu' 
       java-version: '11'

    - name: Build maven project
      run: mvn -B -DskipTests package --file sormas-base/pom.xml
      
    - name: List Current directory
      run: ls -a
    - name: SSH into test server
      run: 217.182.24.129 -| anthony -ssh
