# This is a basic workflow to help you get started with Actions

name: maven build

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Deploy server
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout development branch from github
      uses: actions/checkout@v3

    - name: Set up jdk
      uses: actions/setup-java@v3
      with:
       distribution: 'zulu' 
       java-version: '11'
    - name: Run Ant Target
      run: ant -noinput -buildfile ./sormas-base/build.xml jar
    - name: Package As Artifacts
      uses: actions/upload-artifact@v3
      with:
           name: Package
           path: build/jar
    - name: List Current directory
      run: ls -a
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known host
      run: ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/home/anthony/test_sormas
      
